# Generated by Django 5.1.5 on 2025-07-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
