# Generated by Django 5.1.5 on 2025-07-24 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
